DROP SEQUENCE IF EXISTS TIPO_BEBIDA_SEQ_ID;
DROP SEQUENCE IF EXISTS SECAO_SEQ_ID;
DROP SEQUENCE IF EXISTS HISTORICO_SEQ_ID;

CREATE SEQUENCE TIPO_BEBIDA_SEQ_ID;
CREATE SEQUENCE SECAO_SEQ_ID;
CREATE SEQUENCE HISTORICO_SEQ_ID;

CREATE TABLE IF NOT EXISTS TIPO_BEBIDA
(
  ID     INT PRIMARY KEY,
  VOLUME INT,
  NOME   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SECAO
(
  ID                    INT PRIMARY KEY,
  NOME                  VARCHAR(255),
  TIPO_BEBIDA           INT REFERENCES TIPO_BEBIDA (ID),
  QUANTIDADE_PREENCHIDA INT
);

CREATE TABLE IF NOT EXISTS HISTORICO
(
  ID                    INT PRIMARY KEY,
  SECAO_ID              INT REFERENCES SECAO (ID),
  TIPO_MOVIMENTO        INT,
  TIPO_BEBITA           INT REFERENCES TIPO_BEBIDA (ID),
  RESPONSAVEL_MOVIMENTO VARCHAR(255),
  VOLUME_MOVIMENTADO    INT,
  DATA_MOVIMENTO        DATE
);

-- DELETANDO DADOS DA TABELA
DELETE FROM TIPO_BEBIDA WHERE 1 = 1;
DELETE FROM SECAO WHERE 1 = 1;
DELETE FROM HISTORICO WHERE 1 = 1;

-- CRIACAO DOS TIPOS BEBIDA
INSERT INTO TIPO_BEBIDA VALUES (TIPO_BEBIDA_SEQ_ID.nextval, 'Alcoólicas', 500);
INSERT INTO TIPO_BEBIDA VALUES (TIPO_BEBIDA_SEQ_ID.nextval, 'Não-Alcoólicas', 400);

-- CRIACAO DAS SECOES
INSERT INTO SECAO VALUES ( SECAO_SEQ_ID.nextval, 'seção 1', 0, null  );
INSERT INTO SECAO VALUES ( SECAO_SEQ_ID.nextval, 'seção 2', 0, null  );
INSERT INTO SECAO VALUES ( SECAO_SEQ_ID.nextval, 'seção 3', 0, null  );
INSERT INTO SECAO VALUES ( SECAO_SEQ_ID.nextval, 'seção 4', 0, null  );
INSERT INTO SECAO VALUES ( SECAO_SEQ_ID.nextval, 'seção 5', 0, null  );
